name: ahara_partner
description: "AHRA Partner App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¥ REQUIRED FOR LANGUAGE SUPPORT
  flutter_localizations:
    sdk: flutter

  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10

  provider: ^6.0.5
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  http: ^1.2.0
  url_launcher: ^6.2.5
  firebase_messaging: ^15.2.0
  csv: ^5.0.2
  #path_provider: ^2.1.2
  share_plus: ^7.2.1

  # ðŸ”¥ VERSION MUST MATCH flutter_localizations
  intl: ^0.20.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/partner_types/
    - assets/images/ahra_logo.png
